[project]
name = "webprobe"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = []

[project.scripts]
webprobe = "webprobe:main"

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"
